title = "Ariel's Food Blog"
copyright = "GPL-3.0-only"

[params]
languageName = "English"
displayName = "EN"
isoCode = "en-AU"
logo = "discord-avatar-512-9O706-modified.png"
description = "Very short writeups on food, mostly personal, highly subjective."
dateFormat = "2 January 2006"
weight = 1
rtl = false

[author]
  name = "en author name"
  image = "img/discord-avatar-128-ZTDHXC.gif"
  headline = "en author headline"
  bio = "This is my bio"
  links = [
    { mastodon = "https://eigenmagic.net/@arichtman" },
    { github = "https://github.com/arichtman" },
  ]
