
# https://github.com/getzola/zola/issues/2226
# [[taxonomies]]
# categories = "categories"
# [[taxonomies]]
# ratings = "rating"
# [[taxonomies]]
# manufacturers = "manufacturer"
# [[taxonomies]]
# lines = "line"
